In [2]:
l=range(1000000)

In [3]:
import numpy as np

In [4]:
d=np.arange(1000000)

In [8]:
%time for i in range(1,10): r = [x*2 for x in l]

Wall time: 2.37 s


In [10]:
%time for i in range(1,10): r=d*2

Wall time: 37.9 ms


# A multideminsional

In [11]:
import numpy as np

In [21]:
x = np.zeros((4,4))

In [24]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
np.empty((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# list to convert array

In [7]:
l = [1,2,3,4,5]

In [8]:
l

[1, 2, 3, 4, 5]

In [9]:
print(l)

[1, 2, 3, 4, 5]


In [10]:
np.array(l)

array([1, 2, 3, 4, 5])

In [15]:
x=np.zeros((10,10))

In [16]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
x.shape

(10, 10)

In [18]:
y=x.reshape((2,2,5,5))

In [19]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [21]:
y.dtype

dtype('float64')

In [29]:
import numpy as np

In [31]:
a=np.random.randn((10))

In [32]:
b=np.random.randn((10))

In [33]:
a+b

array([-0.9909864 ,  1.71284626,  0.8054715 ,  1.10587199,  0.47622139,
        0.28544195,  1.46769625,  0.45055864, -1.38702423,  3.1896835 ])

In [34]:
a-b

array([ 1.22937904,  0.40950711,  1.23026603,  1.15453025,  0.7896889 ,
        0.29661675, -2.01448335,  1.5935959 , -3.42216627, -0.57954578])

In [35]:
2*a

array([ 0.23839264,  2.12235337,  2.03573753,  2.26040224,  1.26591029,
        0.5820587 , -0.5467871 ,  2.04415454, -4.8091905 ,  2.61013772])

In [36]:
2*b

array([-2.22036544,  1.30333915, -0.42479453, -0.04865826, -0.31346752,
       -0.0111748 ,  3.48217959, -1.14303726,  2.03514204,  3.76922928])

In [37]:
a>0

array([ True,  True,  True,  True,  True,  True, False,  True, False,
        True])

In [38]:
a[a>0]

array([0.11919632, 1.06117669, 1.01786876, 1.13020112, 0.63295515,
       0.29102935, 1.02207727, 1.30506886])